;PlatformIO Project Configuration File

[env:esp32-c6-devkitc-1]
; --- 核心配置 ---
platform =  https://github.com/platformio/platform-espressif32.git
board = esp32-c6-devkitc-1  ; 如果你是其他特殊型号的C6，可以改成对应名字
framework = arduino

; --- 串口监视器配置 ---
monitor_speed = 115200
; monitor_port = COM3       ; 如果串口识别不准，可以取消注释并强制指定您的 COM 口

; --- 编译参数 (ESP32-C6 常用优化) ---
build_flags = 
    -D CORE_DEBUG_LEVEL=1   ; 调试等级，设为1或0可节省空间
    ; -D ARDUINO_USB_CDC_ON_BOOT=1  ; 【注意】如果您的C6是用Type-C直连芯片(无串口芯片)且看不到打印，请取消这行的注释

; --- 依赖库管理 (非常重要) ---
lib_deps =
    ; 1. 核心绘图库 (您之前提到的 GFX)
    adafruit/Adafruit GFX Library @ ^1.11.9
    
    